### ISSUE TITLE
French--Catalan not working

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-apy#85]
From @TinoDidriksen:

```
Need the APy people to look at this.

APy yields 500 Internal Server Error:
https://www.apertium.org/apy/translate?q=250%20ans%20d%E2%80%99histoire,%20un%20mod%C3%A8le%20p%C3%A9dagogique%20unique,%20une%20ouverture%20sur%20le%20monde%20avec%20de%20nombreux%20partenariats%20avec%20les%20meilleures%20universit%C3%A9s,%20des%20institutions%20culturelles%20de%20premier%20plan%20et%20les%20entreprises%20les%20plus%20innovantes.&langpair=fra|cat

But this works:
echo "250 ans d'histoire, un modèle pédagogique unique, une ouverture sur le monde avec de nombreux partenariats avec les meilleures universités, des institutions culturelles de premier plan et les entreprises les plus innovantes." | sh ~apertium/tarballs-build/share/apertium/modes/fra-cat.mode -g
250 anys d'història, un model pedagògic únic, una obertura sobre el món amb moltes cooperacions amb les millors universitats, de les institucions culturals de primer plànol i les empreses les més *innovantes.

APy log: http://codepad.org/cjtbFI8g
```

**Comment by sushain97** [comment]
This problem also pops up in many other places...

**Comment by xavivars** [comment]
APy tries to load apertium-separable with -z, but `lsx-proc`doesn't support that flag. It can easily be checked by using `pipedebug` mode instead of translate (see https://www.apertium.org/apy/pipedebug?q=250%20ans%20d%E2%80%99histoire,%20un%20mod%C3%A8le%20p%C3%A9dagogique%20unique,%20une%20ouverture%20sur%20le%20monde%20avec%20de%20nombreux%20partenariats%20avec%20les%20meilleures%20universit%C3%A9s,%20des%20institutions%20culturelles%20de%20premier%20plan%20et%20les%20entreprises%20les%20plus%20innovantes.&langpair=fra|cat)

I tried adding `lsx-proc` (here)[https://github.com/apertium/apertium-apy/blob/master/translation.py#L120], but then it doesn't flush and just keeps waiting.

Is there any way to tell APy that a command doesn't support NULLflush and have it, instead, instantiate a new process for each translation? That could be a short term fix (medium/long term should be support `-z` in apertium-separable).

**Comment by sushain97** [comment]
I think translateSimple does that but I haven't looked at the code in a
bit. We would have to hack the handler a bit to use it if it detects
apertium-separable in the pipeline.

**Comment by sushain97** [comment]
Aha, I think you can add to https://github.com/apertium/apertium-apy/blob/master/translation.py#L128, @xavivars .

**Comment by ftyers** [comment]
@xavivars it should be trivial to make -z work, the code is completely based on lttoolbox.

**Comment by ftyers** [comment]
@unhammer I've added a `-z` option and also `lsx_wrapper_null_flush` to the `FSTProcessor.cc` code, can you think of anything I've missed?

**Comment by unhammer** [comment]
Yeah, we used to have more such pairs in that list of things-that-don't-support-nul-flush. Simply adding it there should be a temporary workaround.

**Comment by unhammer** [comment]
@ftyers that ought to do it … you could cp -r lttoolbox/tests and swap the command in proctest.py line  `Popen(["../lttoolbox/lt-proc"] + self.procflags + [tmpd+"/compiled.bin"]` and add something sensible in `lt_proc/__init__.py` to test NUL-flushing

**Comment by xavivars** [comment]
For eng-cat the problem was the perceptron tagger, that has been also solved (even if not released yet). 

Now both pairs work most of the time, but every few hours, #71 happens, and APy needs to be restarted. Closing this one to focus on #71 instead.
